s=input("Enter String :")
space=0;
print(s)
print(len(s))
print(s.capitalize())# capitalize only first latter of the whole string.......
print(s.casefold()) # casefold used for Converting whole String into small case.....
print(s.upper()) # convert all latters of string into uppercase latters.....
print(s.title()) # title used for converting every first character of the word into uppercase....
print(s.center(40,"*"))# occupide 40 latters of string ,use  needed space and, in remain space occupide by "*"..... 
print(s.count("o")) # Count occurace of any alphabet or sub-string in the given string......
print(s.endswith("it")) # finds out if the string ends with given alphabet or sub-string or not.....
print(s.find("o")) # finds out index of given alphabet or sub-string....
print(s.index("o",1)) # finds out index of alphabet or sub-string......
print(s.isalnum()) # finds if the string made with only alphabet and numeric values....
print(s.isalpha()) # finds if the string made with only alphabet .....
print(s.isnumeric()) # finds if the string made with only Numeric values .....
print(s.islower()) # find out if the string is in  lower case or not....
print(s.isupper()) # find out if the string is in  upper case or not....
print(s.isspace()) # finds out if the string contains whitespaces or not.....
print(s.istitle()) # finds out if the string is in the form of title or not....
print(s.lower()) # convert string into lower case....
print(s.upper()) # convert string into upper case.....
print(s.title()) # convert string into title form.....
print(s.replace("o","a")) # replace First character with the second character in the string....... 
print(s.swapcase()) # swap the latter in lower case to uper case and uper case to lower case......